---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-bluegreen-active
  namespace: bluegreen  # Add namespace if needed
spec:
  selector:
    app: calculator-app  # Ensure this label matches the pod labels
  ports:
    - protocol: TCP
      port: 5002         # Port exposed by the service
      targetPort: 5000   # Port on the pod that this service forwards traffic to
  type: ClusterIP        # Define the service type, default is ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-bluegreen-preview
  namespace: bluegreen  # Add namespace if needed
spec:
  selector:
    app: calculator-app  # Ensure this label matches the pod labels
  ports:
    - protocol: TCP
      port: 5002         # Port exposed by the service
      targetPort: 5000   # Port on the pod that this service forwards traffic to
  type: ClusterIP        # Define the service type, default is ClusterIP
