---
apiVersion: v1
kind: Service
metadata:
   name: rollouts-bluegreen-active
spec:
   selector:
     app: calculator-app
   ports:
     port: 5002
     targetPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: rollouts-bluegreen-preview
spec:
  selector:
    app: calculator-app
  ports:
    port: 5002
    targetPort: 5000
---
