---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-bluegreen-active
  namespace: bluegreen  
spec:
  selector:
    app: calculator-app  
  ports:
    - protocol: TCP
      port: 5002         
      targetPort: 5000  
  type: ClusterIP        
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-bluegreen-preview
  namespace: bluegreen  
spec:
  selector:
    app: calculator-app  
  ports:
    - protocol: TCP
      port: 5002         
      targetPort: 5000   
  type: ClusterIP       
